### ISSUE TITLE
ui: not showing all UTXOs in dashboard

### ISSUE THREAD

**Issue by billygarrison** [jamesob/coldcore#30]
OS: Windows 10

Bitcoin Core:
![image](https://user-images.githubusercontent.com/30005204/110242677-8796e080-7f2d-11eb-8c43-2134ee602784.png)

Coldcore: (address formatting glitch reported separately in https://github.com/jamesob/coldcore/issues/29)
![image](https://user-images.githubusercontent.com/30005204/110242690-92ea0c00-7f2d-11eb-93e7-f7605ce43ef4.png)

**Comment by billygarrison** [comment]
Both of the missing UTXOs belong to addresses with two UTXOs.

`tb1q4...` has two UTXOs (in order: ****0.010 tBTC***, 0.0121 tBTC)
`tb1q5...` has two UTXOS (in order: 0.0001 tBTC, ****0.2326 tBTC***)

****UTXO not showing in coldcore***

The order of the transactions doesn't seem to affect the which is shown in coldcore (as I just showed). Not sure what is controlling it. I went through the setup and it rescanned the UTXO set to find more recent transactions, but the two are still missing.

Updated screenshots showing the same two UTXOs are missing:
![image](https://user-images.githubusercontent.com/30005204/110248285-a2298380-7f46-11eb-9217-38078760a0fc.png)
![image](https://user-images.githubusercontent.com/30005204/110248292-a786ce00-7f46-11eb-8629-bac344feb52c.png)

**Comment by jamesob** [comment]
Interesting - there's probably an implicit assumption somewhere in the rendering that expects a single UTXO per address; I'll have to dig into the code to figure out where that might be happening.

**Comment by jamesob** [comment]
Yeah, this is an obvious bug - I was keying UTXO retrieval by address; astounded I didn't leave a TODO to fix this: https://github.com/jamesob/coldcore/blob/master/src/coldcore/main.py#L871-L875
