### ISSUE TITLE
Connect to a remote or local node

### ISSUE THREAD

**Issue by pedromvpg** [jamesob/coldcore#42]
Is there documentation on how to connect Coldcore to an external node running on the same network?
Something like a [Nodl](https://www.nodl.it/) or a RassberryPi4 running [MyNode](https://mynodebtc.com/) or [Umbrell](https://getumbrel.com/).

**Comment by jamesob** [comment]
Hi Pedro, thanks for the issue. In general you should be able to connect to a remote note on your network by starting coldcore with [the `--rpc` flag](https://github.com/jamesob/coldcore#coldcore---rpc-url). I mention this in the README, but I'll add better usage examples.
