### ISSUE TITLE
Always waiting

### ISSUE THREAD

**Issue by matthiasdebernardini** [jamesob/coldcore#8]
both in the dashboard and during setup, same config as [ here  ](https://github.com/jamesob/coldcore/issues/6#issue-772499317)

could it be that theres too many transactions? I see it has 8 UTXOs

**Comment by matthiasdebernardini** [comment]
[this is the problematic line](https://github.com/jamesob/coldcore/blob/d86ad23ee4e107937de5ecad1e22537f50d365f6/src/coldcore/ui.py#L485)

![image](https://user-images.githubusercontent.com/32387851/102889932-d15a4980-445b-11eb-9c7c-cea6e51ff91f.png)

Am I supposed to have something in the bitcoin config? I am running the node with all defaults `bitcoind -testnet`

**Comment by jamesob** [comment]
@matthiasdebernardini I'm not sure what the problem you're reporting here is. What are you waiting for? Is there something not displaying that you would expect?

**Comment by jamesob** [comment]
> this is the problematic line

Yup, the whole point of the setup here is to wait for you to send some balance to that address to test send/receive capabilities. Maybe I could improve the messaging here.

**Comment by matthiasdebernardini** [comment]
I was confused because the coldcore told me that I had 8 UTXOS in the wallet, so I falsely assumed that it would send those testnet bitcoins to itself.

I still have to learn how the coldcard simulator works.

Thanks for replying, I think this wallet is a great idea.

**Comment by matthiasdebernardini** [comment]
![image](https://user-images.githubusercontent.com/32387851/102902091-c1983080-446e-11eb-9005-6341654dcc4d.png)

It's fairly clear now that I look at it, this was user error.

perhaps change 'waiting for transaction' to 'waiting for your transaction to be confirmed by the blockchain (minutes or hours depending on available blockspace)'

I misinterpreted that I was waiting on bitcoin core to assemble the transaction or something.
